### ISSUE TITLE
TypeError: Class constructor ThrottlerGuard cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Cyberuben** [nestjs/throttler#575]
Hi,

I'm trying to use the `ThrottlerGuard` as a global guard. I'm using GraphQL, so I did some extra configuration.

Here's what I've got so far:

```typescript
@Injectable()
export class GqlThrottlerGuard extends ThrottlerGuard {
    getRequestResponse(context: ExecutionContext) {
        const gqlCtx = GqlExecutionContext.create(context);
        const ctx = gqlCtx.getContext();
        return { req: ctx.req, res: ctx.res }
    }
}

@Module({
    imports: [
        // other modules
        ThrottlerModule.forRoot({
            ttl: 10,
            limit: 3,
        }),
        GraphQLModule.forRoot({
            typePaths: ['src/**/*.graphql'],
            formatError,
            introspection: true,
            playground: true,
            context: ({ req, res }) => ({ req, res }),
        }),
        SentryModule.forRoot({
            dsn: process.env.SENTRY_DSN,
            environment: process.env.SENTRY_ENVIRONMENT,
            debug: true,
            tracesSampleRate: 1.0,
            logLevel: LogLevel.Error,
        }),
    ],
    providers: [
        // other providers,
        {
            provide: APP_FILTER,
            useClass: GraphQLErrorFilter,
        },
        {
            provide: APP_GUARD,
            useClass: GqlThrottlerGuard,
        },
    ],
    controllers: [AppController],
})
export class AppModule {
    configure(consumer: MiddlewareConsumer) {
        // configuring some middleware
    }
}
```

This results in the error as described in the title, the full stacktrace can be found here:

```
[0] [Nest] 56196   - 07/14/2021, 2:01:18 PM   [ExceptionHandler] Class constructor ThrottlerGuard cannot be invoked without 'new' +8ms
[0] TypeError: Class constructor ThrottlerGuard cannot be invoked without 'new'
[0]     at new GqlThrottlerGuard (/Users/rubenrutten/Projects/NodeAPI/src/app.module.ts:79:9)
[0]     at Injector.instantiateClass (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/injector.js:286:19)
[0]     at callback (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/injector.js:42:41)
[0]     at Injector.resolveConstructorParams (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/injector.js:114:24)
[0]     at Injector.loadInstance (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/injector.js:46:9)
[0]     at Injector.loadProvider (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/injector.js:68:9)
[0]     at async Promise.all (index 9)
[0]     at InstanceLoader.createInstancesOfProviders (/Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
[0]     at /Users/rubenrutten/Projects/NodeAPI/node_modules/@nestjs/core/injector/instance-loader.js:28:13
[0]     at async Promise.all (index 1)
```

If I replace the `GqlThrottlerGuard` with `ThrottlerGuard`, it starts up fine, but the rate limiting doesn't work on GraphQL endpoints.

What other information could be relevant?

**Comment by jmcdo29** [comment]
That's definitely odd. Do you have a minimum reproduction of this?

**Comment by Cyberuben** [comment]
I'll try to reproduce it in a clean environment tomorrow. Until then, this seems relevant to the issue: https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

Is it possible that there's a mismatch between TypeScript versions / targets?

**Comment by Cyberuben** [comment]
I was able to find the issue on my own. Multiple versions of ts-node were running, causing the application only to show this behavior when running our watch command, which in turn runs nodemon.

Resolved

**Comment by jmcdo29** [comment]
Interesting. I wonder if using the `@nestjs/cli` would change that, as it runs `tsc` and then `node` wand also watches for changes. Might be worth a shot

**Comment by Cyberuben** [comment]
If I run it manually using `node path/to/index` it runs fine. It also compiles fine. Nodemon `9.0.0` was used because it was defined somewhere in my workspace, made sure Nodemon is at the latest version everywhere and it now runs fine too.
